namespace: arcon

name: credential_resolver_dv

version: 1.0.0

readme: README.md

authors:
  - Arcon Tech Solutions

description: Ansible lookup plugin to securely retrieve credentials from ARCON PAM using token-based authentication and dynamic API integration.

license:
  - GPL-2.0-or-later

license_file: ''

tags:
  - security

dependencies: {}

repository: https://github.com/arcon-tech/arcon-ansible-credential-resolver-plugin

documentation: https://github.com/arcon-tech/arcon-ansible-credential-resolver-plugin

homepage: https://github.com/arcon-tech/arcon-ansible-credential-resolver-plugin

issues: https://github.com/arcon-tech/arcon-ansible-credential-resolver-plugin/issues

build_ignore: []
